[Feature]added jwt authentication
RahulRimal/ccib_api pull request #16
Opened 2024-05-19 13:01 UTC by arj9912

2024-05-20 07:47 UTC, RahulRimal requested changes

2024-05-20 07:47 UTC, RahulRimal commented on autho/urls.py
> +from rest_framework_simplejwt.views import TokenVerifyView, TokenObtainPairView, TokenRefreshView
import from autho's view and not from library's view

2024-05-20 07:47 UTC, RahulRimal commented on autho/urls.py
> +    # path('register/', views.register_user, name='register'),
remove this

2024-05-20 07:47 UTC, RahulRimal commented on autho/views.py
> +from django.http import HttpRequest
fix the import order
python libraries at top
then django libraries
then rest_framework libraries
then third_party libraries
finally own custom apps imports

2024-05-20 07:47 UTC, RahulRimal commented on autho/views.py
> +    # def me(self, request):
remove commented code

2024-05-20 08:04 UTC, arj9912 commented on autho/urls.py
> +from rest_framework_simplejwt.views import TokenVerifyView, TokenObtainPairView, TokenRefreshView
done

2024-05-20 08:05 UTC, arj9912 commented on autho/urls.py
> +    # path('register/', views.register_user, name='register'),
done

2024-05-20 08:05 UTC, arj9912 commented on autho/views.py
> +    # def me(self, request):
done

2024-05-20 09:11 UTC, RahulRimal requested changes

2024-05-20 09:11 UTC, RahulRimal commented on autho/urls.py
> +from rest_framework_simplejwt.views import TokenVerifyView, TokenObtainPairView, TokenRefreshView
make line 2 from . import views
and delete line 3

2024-05-20 09:11 UTC, RahulRimal commented on autho/urls.py
> +router.register('users', autho_views.UserViewSet, basename='users')
make autho_views.UserViewSet to views.UserViewSet

2024-05-20 09:11 UTC, RahulRimal commented on autho/urls.py
>      path("create-token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
make TokenObtainPairView.as_view() to views.TokenObtainPairView.as_view()

2024-05-20 09:11 UTC, RahulRimal commented on autho/urls.py
>      path("refresh-token/",TokenRefreshView.as_view(), name="token_refresh"),
make TokenRefreshView.as_view() to views.TokenRefreshView.as_view()

2024-05-20 09:11 UTC, RahulRimal commented on autho/urls.py
>      path("verify-token/", TokenVerifyView.as_view(), name="token_verify"),
make TokenVerifyView.as_view() to views.TokenVerifyView.as_view()

2024-05-20 09:24 UTC, arj9912 commented on autho/urls.py
> +router.register('users', autho_views.UserViewSet, basename='users')
ok done

2024-05-20 09:24 UTC, arj9912 commented on autho/urls.py
>      path("create-token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
ok done

2024-05-20 09:24 UTC, arj9912 commented on autho/urls.py
>      path("refresh-token/",TokenRefreshView.as_view(), name="token_refresh"),
ok done

2024-05-20 09:24 UTC, arj9912 commented on autho/urls.py
>      path("verify-token/", TokenVerifyView.as_view(), name="token_verify"),
ok done

2024-05-20 09:53 UTC, arj9912 commented on autho/urls.py
> +from rest_framework_simplejwt.views import TokenVerifyView, TokenObtainPairView, TokenRefreshView
ok done

2024-05-21 14:00 UTC, RahulRimal requested changes

2024-05-21 14:00 UTC, RahulRimal commented on autho/views.py
> +        old_password = request.data.get("old_password")
here check if request.user.is_authenticated
if not authenticated then show error saying must be logged in to change password

2024-05-22 13:20 UTC, RahulRimal approved these changes

2024-05-22 13:20 UTC, merged