[Feature]added user model and cooperative model
RahulRimal/ccib_api pull request #17
Opened 2024-05-22 06:16 UTC by arj9912

2024-05-22 13:29 UTC, RahulRimal requested changes

2024-05-22 13:29 UTC, RahulRimal commented on cooperative/models.py
> +        (TYPE_TERM, "Term"),
change TYPE_TERM to NATURE_TERM and TYPE_OVERDRAFT to NATURE_OVERDRAFT

2024-05-22 13:29 UTC, RahulRimal commented on cooperative/models.py
> +    due_date = models.DateField(default=now)
remove default

2024-05-22 13:29 UTC, RahulRimal commented on cooperative/models.py
> +    LOAN_TYPE_REAL_ESTATE = "real estate"
remove LOAN_ from and make TYPE_REAL_ESTATE and so on

2024-05-22 13:29 UTC, RahulRimal commented on cooperative/models.py
> +    LOAN_TYPE_CHOICES = [
make LOAN_TYPE_CHOICES to TYPE_CHOICES

2024-05-24 07:13 UTC, arj9912 commented on cooperative/models.py
> +        (TYPE_TERM, "Term"),
done

2024-05-24 07:13 UTC, arj9912 commented on cooperative/models.py
> +    due_date = models.DateField(default=now)
done

2024-05-24 07:13 UTC, arj9912 commented on cooperative/models.py
> +    LOAN_TYPE_REAL_ESTATE = "real estate"
done

2024-05-24 07:13 UTC, arj9912 commented on cooperative/models.py
> +    LOAN_TYPE_CHOICES = [
done

2024-05-24 12:07 UTC, RahulRimal requested changes

2024-05-24 12:07 UTC, RahulRimal commented on cooperative/serializers.py
> +    loan = LoanSerializer(read_only=True)
Remove commented code

2024-05-24 12:07 UTC, RahulRimal commented on cooperative/serializers.py
> +class CreateSecuritySerializer(BaseModelSerializerMixin):
Rename to CreateSecurityDepositSerializer

2024-05-24 14:49 UTC, arj9912 commented on cooperative/models.py
> +from django.utils.timezone import now
ok done

2024-05-24 14:49 UTC, arj9912 commented on cooperative/models.py
> +    def __str__(self):
ok done

2024-05-24 14:49 UTC, arj9912 commented on cooperative/models.py
> +class Security(BaseModelMixin):
ok done

2024-05-24 14:49 UTC, arj9912 commented on cooperative/models.py
> +        (TYPE_REAL_ESTATE, "Real State"),
ok done

2024-05-24 14:49 UTC, arj9912 commented on cooperative/models.py
> +        return self.loan.account_number
ok done

2024-05-24 14:52 UTC, arj9912 commented on cooperative/serializers.py
> +    Security,
ok done

2024-05-24 14:53 UTC, arj9912 commented on cooperative/serializers.py
> +    loan = LoanSerializer(read_only=True)
ok done

2024-05-24 14:53 UTC, arj9912 commented on cooperative/serializers.py
> +class CreateSecuritySerializer(BaseModelSerializerMixin):
ok done

2024-05-25 05:42 UTC, RahulRimal requested changes

2024-05-25 05:42 UTC, RahulRimal commented on autho/models.py
> +    grandfathers_name = models.CharField(max_length=255)
change to grandfather_name

2024-05-25 05:42 UTC, RahulRimal commented on autho/serializers.py
> +            "grandfathers_name",
change to grandfather_name

2024-05-25 05:42 UTC, RahulRimal commented on cooperative/models.py
> +    STATUS_GOOD = "Good"
change to good

2024-05-25 05:42 UTC, RahulRimal commented on cooperative/models.py
> +    STATUS_NPL = "Non-Performing Loan"
change to npl

2024-05-25 05:42 UTC, RahulRimal commented on cooperative/models.py
> +        (STATUS_GOOD, "Good"),
use STATUS_GOOD.capitalize() instead of "Good"

2024-05-25 05:42 UTC, RahulRimal commented on cooperative/models.py
> +        (OWNERSHIP_OWN, "Own"),
change to OWNERSHIP_WON.capitalize() instead

2024-05-25 06:02 UTC, arj9912 commented on autho/models.py
> +    grandfathers_name = models.CharField(max_length=255)
ok done

2024-05-25 06:02 UTC, arj9912 commented on autho/serializers.py
> +            "grandfathers_name",
ok done

2024-05-25 06:02 UTC, arj9912 commented on cooperative/models.py
> +    STATUS_GOOD = "Good"
ok done

2024-05-25 06:03 UTC, arj9912 commented on cooperative/models.py
> +    STATUS_NPL = "Non-Performing Loan"
ok done

2024-05-25 06:03 UTC, arj9912 commented on cooperative/models.py
> +        (STATUS_GOOD, "Good"),
ok done

2024-05-25 06:03 UTC, arj9912 commented on cooperative/models.py
> +        (OWNERSHIP_OWN, "Own"),
ok done

2024-05-25 06:34 UTC, RahulRimal requested changes

2024-05-25 06:34 UTC, RahulRimal commented on cooperative/models.py
> +    STATUS_BAD_DEBT = "bad Debt"
make it bad dept

2024-05-25 06:34 UTC, RahulRimal commented on cooperative/models.py
> +    STATUS_NPL = "npl"
add comment saying non performing loan

2024-05-25 06:39 UTC, arj9912 commented on cooperative/models.py
> +    STATUS_BAD_DEBT = "bad Debt"
ok done

2024-05-25 06:39 UTC, arj9912 commented on cooperative/models.py
> +    STATUS_NPL = "npl"
ok done

2024-05-25 07:00 UTC, merged