[Feature KAN-5]added subscriptions
RahulRimal/ccib_api pull request #6
Opened 2024-05-13 15:41 UTC by arj9912

2024-05-14 07:53 UTC, RahulRimal commented on subscription/views.py
> +    def get_serializer_class(self):
remove this

2024-05-14 07:53 UTC, RahulRimal commented on subscription/views.py
> +    # serializer_class = PlanCostSerializer
uncomment this

2024-05-14 07:54 UTC, RahulRimal commented on subscription/views.py
> +    def get_serializer_class(self):
remove this

2024-05-14 08:20 UTC, arj9912 commented on ccib/settings.py
> +ALLOWED_HOSTS = [
ok arko localsetting banayarw rakhne ho

2024-05-14 08:21 UTC, arj9912 commented on ccib/urls.py
> +import subscriptions
ok done

2024-05-14 08:21 UTC, arj9912 commented on cooperative/serializers.py
> +class CreateFinanceSerializer(BaseModelSerializerMixin):
ok done

2024-05-14 08:21 UTC, arj9912 commented on cooperative/serializers.py
> +class UpdateFinanceSerializer(BaseModelSerializerMixin):
ok done

2024-05-14 08:21 UTC, arj9912 commented on cooperative/views.py
> +    def get_serializer_class(self):
ok done

2024-05-14 08:21 UTC, arj9912 commented on subscription/models.py
> +    PERIOD_YEARLY = "yearly"
ok done

2024-05-14 08:21 UTC, arj9912 commented on subscription/models.py
> +    last_bill_paid = models.DateField()
ok done

2024-05-14 08:21 UTC, arj9912 commented on subscription/models.py
> +    next_billing = models.DateField()
ok done

2024-05-14 08:21 UTC, arj9912 commented on subscription/models.py
> +    verified = models.BooleanField(default=False)
ok done

2024-05-14 08:22 UTC, arj9912 commented on subscription/serializers.py
> +class CreatePlanSerializer(BaseModelSerializerMixin):
ok done

2024-05-14 08:22 UTC, arj9912 commented on subscription/serializers.py
> +class UpdatePlanSerializer(BaseModelSerializerMixin):
ok done

2024-05-14 08:22 UTC, arj9912 commented on subscription/serializers.py
> +class CreatePlanCostSerializer(BaseModelSerializerMixin):
ok done

2024-05-14 08:22 UTC, arj9912 commented on subscription/serializers.py
> +class UpdatePlanCostSerializer(BaseModelSerializerMixin):
ok done

2024-05-14 08:22 UTC, arj9912 commented on subscription/views.py
> +# Create your views here.
ok done

2024-05-14 08:22 UTC, arj9912 commented on subscription/views.py
> +    # serializer_class = PlanSerializer
ok done

2024-05-14 08:22 UTC, arj9912 commented on subscription/views.py
> +    def get_serializer_class(self):
ok done

2024-05-14 08:22 UTC, arj9912 commented on subscription/views.py
> +    # serializer_class = PlanCostSerializer
ok done

2024-05-14 08:23 UTC, arj9912 commented on subscription/views.py
> +    def get_serializer_class(self):
ok done

2024-05-14 08:27 UTC, RahulRimal commented on ccib/settings.py
> +ALLOWED_HOSTS = [
yes. BM hernu na testae ho

2024-05-14 08:34 UTC, RahulRimal requested changes

2024-05-14 08:34 UTC, RahulRimal commented on subscription/models.py
> +    billing_start = models.DateField(null=True, blank=True)
yo null and blank hudaina

2024-05-14 08:34 UTC, RahulRimal commented on subscription/models.py
> +    billing_end = models.DateField(null=True, blank=True)
yo null and blank hudaina

2024-05-14 08:34 UTC, RahulRimal commented on subscription/models.py
> +    next_billing = models.DateField(null=True, blank=True)
yo null and blank hudaina

2024-05-14 08:40 UTC, arj9912 commented on ccib/settings.py
> +ALLOWED_HOSTS = [
eaa lwlw hunxa

2024-05-14 10:36 UTC, arj9912 commented on subscription/models.py
> +    next_billing = models.DateField(null=True, blank=True)
ok done

2024-05-14 10:36 UTC, arj9912 commented on subscription/models.py
> +    billing_end = models.DateField(null=True, blank=True)
ok done

2024-05-14 10:36 UTC, arj9912 commented on ccib/settings.py
> +ALLOWED_HOSTS = [
ok dai

2024-05-15 06:45 UTC, RahulRimal requested changes

2024-05-15 06:45 UTC, RahulRimal commented on ccib/urls.py
> +    path('subscription/', include('subscription.urls')),
remove this

2024-05-15 07:04 UTC, arj9912 commented on ccib/urls.py
> +    path('subscription/', include('subscription.urls')),
ok done

2024-05-15 07:06 UTC, RahulRimal approved these changes

2024-05-15 07:07 UTC, merged