[Feature]Feature/arjun/subscription
RahulRimal/ccib_api pull request #9
Opened 2024-05-15 12:25 UTC by arj9912

2024-05-15 12:35 UTC, RahulRimal requested changes

2024-05-15 12:35 UTC, RahulRimal commented on subscription/models.py
> +    recurrance_period = models.DateField()
move this to Subscription

2024-05-15 12:35 UTC, RahulRimal commented on subscription/serializers.py
> +        fields = ["idx", "price", "recurrance_period"]
remove recurrance_period

2024-05-15 12:35 UTC, RahulRimal commented on subscription/serializers.py
>          ]
add recurrance_period too

2024-05-15 12:35 UTC, RahulRimal commented on subscription/serializers.py
> +        return super().create(validated_data)
calculate recurrance_period and then add to subscription

2024-05-15 13:32 UTC, arj9912 commented on subscription/models.py
> +    recurrance_period = models.DateField()
ok done

2024-05-15 13:32 UTC, arj9912 commented on subscription/serializers.py
> +        fields = ["idx", "price", "recurrance_period"]
ok done

2024-05-15 13:32 UTC, arj9912 commented on subscription/serializers.py
>          ]
ok done

2024-05-15 13:32 UTC, arj9912 commented on subscription/serializers.py
> +        return super().create(validated_data)
ok done

2024-05-18 07:25 UTC, RahulRimal approved these changes

2024-05-18 07:34 UTC, merged